### PR TITLE
add target meta

### PR DESCRIPTION
**Pull request by kwidoo**
Added customization of target field

### CODE REVIEW

**Comment by kitbs** [comment]
Thanks @kwidoo. I do like the ability to customise the target and will definitely consider this idea.

The problem I see is that this will be a breaking change because the current default behaviour is to open in a new tab. And unless every user of this package adds `->target()` to all of their existing fields, to set the default target, their links will suddenly start opening in the same tab.

I think I might prefer something like:

```php
public function sameTab(bool $sameTab = true)
{
    return $this->withMeta(['sameTab' => $sameTab]);
}
```

```vue
<template>
        <div>
            <a :href="field.value"
                :title="field.value"
                v-if="field.value && clickable"
                class="cursor-pointer dim no-underline text-primary flex items-center"
                :target="field.sameTab ? '_self' : '_blank'"
            >
...
```

I don't believe there is much use for target values other than `_self` and `_blank` in HTML5 nowadays, is there? I can't imagine anyone using Nova inside an `<iframe>`...

**Comment by kwidoo** [comment]
In fact it still uses default value as _blank

`public function target(string $target = '_blank')`

But I agree with you, your solution is better. It eliminate possible incorrect values for target.

**Comment by kitbs** [comment]
Yes, I see the method parameter has a default value, but unless the method is actually called on the field, the meta key will be empty (actually not even exist).

I have updated the two files with our new solution and will recompile field.js, test and merge as soon as I can.

Thanks again for your suggestion!

**Comment by kwidoo** [comment]
Thanks Kit, it is good to learn from wiseman ;)

**Comment by kosmonowt** [comment]
@kitbs a merge is highly appreciated! thanks for sharing your work!

**Pull request merged**
