### PR TITLE
support nova 4 and vue 3

### PR DESCRIPTION
**Pull request by max-zu**

### CODE REVIEW

**Comment by bogomya** [comment]
@kitbs please review

**Comment by kitbs** [comment]
@max-zu Thank you so much for your PR. I will review as soon as I can.

**Comment by justkidding96** [comment]
@kitbs What is the ETA of this pull request?

**Comment by tominal** [comment]
I tested the fork on my Nova 4 project and it only displays a full text URL on the index / show pages. Nothing on the edit page.

**Comment by kitbs** [comment]
Thank you for this contribution. I have added Nova 4 support in version 2.0 https://github.com/inspheric/nova-url-field/releases/tag/v2.0.

**Pull request closed without merging**
